import type { Metadata } from "next";
import Link from "next/link";
import { Nav } from "~/components/landing/Nav";
import { Footer } from "~/components/landing/Footer";
import { Thumb } from "~/components/ui/Thumb";
import { TEMPLATES } from "~/lib/engine/templates";

export const metadata: Metadata = {
  title: "Build guides",
  description:
    "Step-by-step hardware build guides for Arduino, ESP32 and Pico — from motion alarms to plant waterers. Pick a project and start building.",
  openGraph: {
    title: "Build guides | Wirecraft",
    description: "Step-by-step hardware build guides for Arduino, ESP32 and Pico.",
  },
};

export default async function GuidesPage({ searchParams }: { searchParams: Promise<{ category?: string }> }) {
  const params = await searchParams;
  const categories = [...new Set(TEMPLATES.map((t) => t.category))].sort();
  const active = params.category;
  const shown = active ? TEMPLATES.filter((t) => t.category === active) : TEMPLATES;

  return (
    <>
      <Nav />
      <main className="mx-auto max-w-6xl px-4 py-12 sm:px-6">
        <p className="eyebrow">Guides</p>
        <h1 className="mt-2 font-display text-4xl font-bold tracking-tight">Build guides</h1>
        <p className="mt-2 max-w-[52ch] text-muted">
          Every guide is generated by the same engine that powers the workbench — full wiring,
          firmware, parts and assembly steps. Open one, then remix it in chat.
        </p>

        <div className="mt-6 flex flex-wrap gap-2">
          <Link href="/guides" className={`chip ${!active ? "chip-active" : ""}`}>
            All
          </Link>
          {categories.map((c) => (
            <Link key={c} href={`/guides?category=${encodeURIComponent(c)}`} className={`chip ${active === c ? "chip-active" : ""}`}>
              {c}
            </Link>
          ))}
        </div>

        <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {shown.map((t, i) => (
            <Link key={t.slug} href={`/guides/${t.slug}`} className="card group overflow-hidden transition hover:-translate-y-0.5 hover:shadow-pop">
              <div className="aspect-[16/10] border-b border-line">
                <Thumb hue={t.hue} icon={t.icon} seed={i} />
              </div>
              <div className="p-4">
                <p className="font-mono text-[10px] font-semibold uppercase tracking-widest text-muted">
                  {t.category} · {t.board.replace("arduino-uno", "Arduino Uno").replace("esp32", "ESP32").replace("pico", "Pico")}
                </p>
                <h2 className="mt-1 font-display text-base font-semibold">{t.title}</h2>
                <p className="mt-1 text-sm text-muted">{t.summary}</p>
              </div>
            </Link>
          ))}
        </div>
      </main>
      <Footer />
    </>
  );
}
