import type { CatalogComponent } from "./types";

const C = {
  red: "#E5484D",
  black: "#17191E",
  yellow: "#F0B100",
  green: "#2FA36B",
  blue: "#2B4BF2",
  orange: "#E87A2F",
  purple: "#8B5CF6",
  white: "#B9BCC4",
};

export const CATALOG: CatalogComponent[] = [
  {
    id: "led",
    name: "LED (5 mm) + 220 Ω resistor",
    shortName: "LED",
    category: "Output",
    keywords: ["led", "light", "blink", "lamp", "indicator", "status"],
    summary: "A basic indicator light. Always pair with a current-limiting resistor.",
    price: 0.15,
    pins: [
      { name: "ANODE", kind: "digital", color: C.yellow },
      { name: "CATHODE", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:ANODE}"],
      globals: [],
      setup: ["pinMode({REF}_PIN, OUTPUT);"],
      loop: [],
    },
    actuate: { on: "digitalWrite({REF}_PIN, HIGH);", off: "digitalWrite({REF}_PIN, LOW);" },
    buildTip: "The longer leg is the anode (+). The resistor can go on either leg.",
  },
  {
    id: "button",
    name: "Tactile push button",
    shortName: "Button",
    category: "Input",
    keywords: ["button", "press", "switch", "toggle", "input"],
    summary: "Momentary switch, wired with the internal pull-up so no extra resistor is needed.",
    price: 0.1,
    pins: [
      { name: "SIG", kind: "digital", color: C.blue },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:SIG}"],
      globals: ["bool {ref}Pressed = false;"],
      setup: ["pinMode({REF}_PIN, INPUT_PULLUP);"],
      loop: ["{ref}Pressed = (digitalRead({REF}_PIN) == LOW);"],
    },
    readingVar: "{ref}Pressed",
    buildTip: "Legs on the same side are connected in pairs — wire diagonally opposite corners to be safe.",
  },
  {
    id: "ultrasonic",
    name: "HC-SR04 ultrasonic ranger",
    shortName: "Ultrasonic",
    category: "Sensor",
    keywords: ["distance", "ultrasonic", "parking", "range", "proximity", "sonar", "radar"],
    summary: "Measures distance from 2 cm to ~4 m by timing an ultrasonic echo.",
    price: 1.9,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 5 },
      { name: "TRIG", kind: "digital", color: C.green },
      { name: "ECHO", kind: "digital", color: C.yellow },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_TRIG {PIN:TRIG}", "#define {REF}_ECHO {PIN:ECHO}"],
      globals: ["float {ref}Cm = 0;"],
      setup: ["pinMode({REF}_TRIG, OUTPUT);", "pinMode({REF}_ECHO, INPUT);"],
      loop: ["{ref}Cm = readUltrasonicCm({REF}_TRIG, {REF}_ECHO);"],
      helpers: [
        "float readUltrasonicCm(int trigPin, int echoPin) {",
        "  digitalWrite(trigPin, LOW); delayMicroseconds(2);",
        "  digitalWrite(trigPin, HIGH); delayMicroseconds(10);",
        "  digitalWrite(trigPin, LOW);",
        "  long us = pulseIn(echoPin, HIGH, 30000UL);",
        "  return us > 0 ? us / 58.0f : -1.0f;",
        "}",
      ],
    },
    readingVar: "{ref}Cm",
    buildTip: "On 3.3 V boards, put a voltage divider (1 kΩ / 2 kΩ) on ECHO — the module echoes at 5 V.",
  },
  {
    id: "dht22",
    name: "DHT22 temperature & humidity sensor",
    shortName: "DHT22",
    category: "Sensor",
    keywords: ["temperature", "humidity", "weather", "climate", "thermometer", "dht"],
    summary: "Digital sensor for ambient temperature (±0.5 °C) and relative humidity.",
    price: 4.5,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 3.3 },
      { name: "DATA", kind: "digital", color: C.green },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: ["adafruit/DHT sensor library@^1.4.6", "adafruit/Adafruit Unified Sensor@^1.1.14"],
    code: {
      includes: ["#include <DHT.h>"],
      defines: ["#define {REF}_PIN {PIN:DATA}"],
      globals: ["DHT {ref}(({uint8_t}){REF}_PIN, DHT22);", "float {ref}TempC = 0, {ref}Humidity = 0;"],
      setup: ["{ref}.begin();"],
      loop: [
        "{ref}TempC = {ref}.readTemperature();",
        "{ref}Humidity = {ref}.readHumidity();",
      ],
    },
    readingVar: "{ref}TempC",
    buildTip: "Give it 2 seconds between reads — the DHT22 is slow but steady.",
  },
  {
    id: "oled",
    name: "SSD1306 OLED display (128×64, I²C)",
    shortName: "OLED",
    category: "Display",
    keywords: ["display", "screen", "oled", "show", "clock", "dashboard", "readout"],
    summary: "Crisp 0.96\" monochrome display on the I²C bus — two data wires, endless dashboards.",
    price: 3.2,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 3.3 },
      { name: "GND", kind: "gnd", color: C.black },
      { name: "SDA", kind: "i2c-sda", color: C.blue },
      { name: "SCL", kind: "i2c-scl", color: C.purple },
    ],
    libs: ["adafruit/Adafruit SSD1306@^2.5.10", "adafruit/Adafruit GFX Library@^1.11.9"],
    code: {
      includes: ["#include <Wire.h>", "#include <Adafruit_GFX.h>", "#include <Adafruit_SSD1306.h>"],
      globals: ["Adafruit_SSD1306 {ref}(128, 64, &Wire, -1);"],
      setup: [
        "if (!{ref}.begin(SSD1306_SWITCHCAPVCC, 0x3C)) { Serial.println(F(\"OLED not found\")); }",
        "{ref}.clearDisplay();",
        "{ref}.setTextColor(SSD1306_WHITE);",
        "{ref}.setTextSize(1);",
      ],
      loop: [],
    },
    buildTip: "If nothing shows up, try I²C address 0x3D — some modules ship with it.",
  },
  {
    id: "buzzer",
    name: "Passive piezo buzzer",
    shortName: "Buzzer",
    category: "Output",
    keywords: ["buzzer", "beep", "alarm", "sound", "tone", "siren", "alert"],
    summary: "Plays tones with the tone() function — from gentle chirps to full alarms.",
    price: 0.6,
    pins: [
      { name: "SIG", kind: "pwm", color: C.orange },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:SIG}"],
      globals: [],
      setup: ["pinMode({REF}_PIN, OUTPUT);"],
      loop: [],
    },
    actuate: { on: "tone({REF}_PIN, 880);", off: "noTone({REF}_PIN);" },
    buildTip: "Passive buzzers need tone(); active ones just want HIGH. This design assumes passive.",
  },
  {
    id: "servo",
    name: "SG90 micro servo",
    shortName: "Servo",
    category: "Actuator",
    keywords: ["servo", "arm", "rotate", "dispenser", "feeder", "lock", "flap", "door"],
    summary: "180° positional servo — the workhorse of latches, feeders and flags.",
    price: 2.4,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 5 },
      { name: "SIG", kind: "pwm", color: C.orange },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: ["arduino-libraries/Servo@^1.2.1"],
    code: {
      includes: ["#include <Servo.h>"],
      defines: ["#define {REF}_PIN {PIN:SIG}"],
      globals: ["Servo {ref};"],
      setup: ["{ref}.attach({REF}_PIN);", "{ref}.write(0);"],
      loop: [],
    },
    actuate: { on: "{ref}.write(90);", off: "{ref}.write(0);" },
    buildTip: "Servos are power-hungry. For more than one, feed them from a separate 5 V supply and share GND.",
  },
  {
    id: "pir",
    name: "HC-SR501 PIR motion sensor",
    shortName: "PIR",
    category: "Sensor",
    keywords: ["motion", "pir", "presence", "intruder", "security", "movement", "occupancy"],
    summary: "Detects warm bodies moving up to ~7 m away. The classic security-project sensor.",
    price: 1.5,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 5 },
      { name: "OUT", kind: "digital", color: C.green },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:OUT}"],
      globals: ["bool {ref}Motion = false;"],
      setup: ["pinMode({REF}_PIN, INPUT);"],
      loop: ["{ref}Motion = (digitalRead({REF}_PIN) == HIGH);"],
    },
    readingVar: "{ref}Motion",
    buildTip: "Give it 30–60 s to settle after power-up, and turn both trim pots fully counter-clockwise to start.",
  },
  {
    id: "ldr",
    name: "Photoresistor (LDR) + 10 kΩ divider",
    shortName: "Light sensor",
    category: "Sensor",
    keywords: ["light", "brightness", "dark", "ldr", "photoresistor", "sunlight", "dusk"],
    summary: "Reads ambient brightness through a simple voltage divider.",
    price: 0.4,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 3.3 },
      { name: "SIG", kind: "analog", color: C.yellow },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:SIG}"],
      globals: ["int {ref}Level = 0;"],
      setup: [],
      loop: ["{ref}Level = analogRead({REF}_PIN);"],
    },
    readingVar: "{ref}Level",
    buildTip: "LDR to VCC, 10 kΩ to GND, read the midpoint. Brighter light = higher reading.",
  },
  {
    id: "soil",
    name: "Capacitive soil moisture sensor",
    shortName: "Soil sensor",
    category: "Sensor",
    keywords: ["soil", "plant", "moisture", "water", "garden", "irrigation", "flower"],
    summary: "Corrosion-resistant probe that reads how thirsty your plant is.",
    price: 1.8,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 3.3 },
      { name: "AOUT", kind: "analog", color: C.yellow },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:AOUT}"],
      globals: ["int {ref}Moisture = 0;"],
      setup: [],
      loop: ["{ref}Moisture = analogRead({REF}_PIN);"],
    },
    readingVar: "{ref}Moisture",
    buildTip: "Calibrate: note the reading in dry air and in a glass of water — your range lives between them.",
  },
  {
    id: "relay",
    name: "1-channel relay module (5 V)",
    shortName: "Relay",
    category: "Actuator",
    keywords: ["relay", "pump", "appliance", "switch", "mains", "fan", "valve", "water"],
    summary: "Lets your microcontroller switch pumps, fans and lamps it could never drive directly.",
    price: 1.2,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 5 },
      { name: "IN", kind: "digital", color: C.green },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:IN}"],
      globals: [],
      setup: ["pinMode({REF}_PIN, OUTPUT);", "digitalWrite({REF}_PIN, LOW);"],
      loop: [],
    },
    actuate: { on: "digitalWrite({REF}_PIN, HIGH);", off: "digitalWrite({REF}_PIN, LOW);" },
    buildTip: "Most cheap modules are active-LOW — if yours clicks backwards, swap HIGH/LOW in the code.",
  },
  {
    id: "neopixel",
    name: "WS2812B NeoPixel ring (8 px)",
    shortName: "NeoPixel",
    category: "Output",
    keywords: ["neopixel", "rgb", "mood", "color", "ws2812", "strip", "ring", "ambient", "disco"],
    summary: "Individually addressable RGB pixels — one data wire, all the colors.",
    price: 3.8,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 5 },
      { name: "DIN", kind: "digital", color: C.green },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: ["adafruit/Adafruit NeoPixel@^1.12.0"],
    code: {
      includes: ["#include <Adafruit_NeoPixel.h>"],
      defines: ["#define {REF}_PIN {PIN:DIN}", "#define {REF}_COUNT 8"],
      globals: ["Adafruit_NeoPixel {ref}({REF}_COUNT, {REF}_PIN, NEO_GRB + NEO_KHZ800);"],
      setup: ["{ref}.begin();", "{ref}.setBrightness(60);", "{ref}.show();"],
      loop: [],
    },
    actuate: {
      on: "{ref}.fill({ref}.Color(43, 75, 242)); {ref}.show();",
      off: "{ref}.clear(); {ref}.show();",
    },
    buildTip: "Add a 330 Ω resistor on DIN and a 470 µF cap across power for happy pixels.",
  },
  {
    id: "pot",
    name: "10 kΩ potentiometer",
    shortName: "Potentiometer",
    category: "Input",
    keywords: ["knob", "potentiometer", "dial", "volume", "adjust", "pot"],
    summary: "A knob that reads 0–100 %. Perfect for thresholds, brightness and volume.",
    price: 0.5,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 3.3 },
      { name: "WIPER", kind: "analog", color: C.yellow },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:WIPER}"],
      globals: ["int {ref}Value = 0;"],
      setup: [],
      loop: ["{ref}Value = analogRead({REF}_PIN);"],
    },
    readingVar: "{ref}Value",
    buildTip: "Outer legs to VCC and GND, middle leg (wiper) to the analog pin.",
  },
  {
    id: "rfid",
    name: "RC522 RFID reader (SPI)",
    shortName: "RFID",
    category: "Sensor",
    keywords: ["rfid", "card", "tag", "badge", "access", "treasure", "nfc", "unlock"],
    summary: "Reads 13.56 MHz cards and fobs — the key to access-control and treasure-chest builds.",
    price: 2.9,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 3.3 },
      { name: "SDA", kind: "digital", color: C.blue },
      { name: "RST", kind: "digital", color: C.white },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: ["miguelbalboa/MFRC522@^1.4.11"],
    code: {
      includes: ["#include <SPI.h>", "#include <MFRC522.h>"],
      defines: ["#define {REF}_SS {PIN:SDA}", "#define {REF}_RST {PIN:RST}"],
      globals: ["MFRC522 {ref}({REF}_SS, {REF}_RST);", "bool {ref}CardPresent = false;"],
      setup: ["SPI.begin();", "{ref}.PCD_Init();"],
      loop: [
        "{ref}CardPresent = {ref}.PICC_IsNewCardPresent() && {ref}.PICC_ReadCardSerial();",
      ],
    },
    readingVar: "{ref}CardPresent",
    buildTip: "SPI pins (SCK/MOSI/MISO) go to the board's hardware SPI header — the diagram labels the two that vary.",
  },
  {
    id: "gas",
    name: "MQ-135 air quality sensor",
    shortName: "Air sensor",
    category: "Sensor",
    keywords: ["air", "gas", "co2", "quality", "smoke", "pollution", "fume"],
    summary: "Sniffs out CO₂-equivalent gases, smoke and general bad air.",
    price: 2.2,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 5 },
      { name: "AOUT", kind: "analog", color: C.yellow },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_PIN {PIN:AOUT}"],
      globals: ["int {ref}Air = 0;"],
      setup: [],
      loop: ["{ref}Air = analogRead({REF}_PIN);"],
    },
    readingVar: "{ref}Air",
    buildTip: "Let it burn in for 24 h before trusting the numbers — the heater needs to settle.",
  },
  {
    id: "encoder",
    name: "KY-040 rotary encoder",
    shortName: "Encoder",
    category: "Input",
    keywords: ["encoder", "rotary", "scroll", "menu", "click", "wheel"],
    summary: "Endless rotation with a push-click — the perfect menu controller.",
    price: 1.1,
    pins: [
      { name: "VCC", kind: "power", color: C.red, volts: 3.3 },
      { name: "CLK", kind: "digital", color: C.blue },
      { name: "DT", kind: "digital", color: C.green },
      { name: "SW", kind: "digital", color: C.yellow },
      { name: "GND", kind: "gnd", color: C.black },
    ],
    libs: [],
    code: {
      includes: [],
      defines: ["#define {REF}_CLK {PIN:CLK}", "#define {REF}_DT {PIN:DT}", "#define {REF}_SW {PIN:SW}"],
      globals: ["int {ref}Position = 0;", "int {ref}LastClk = HIGH;"],
      setup: [
        "pinMode({REF}_CLK, INPUT);",
        "pinMode({REF}_DT, INPUT);",
        "pinMode({REF}_SW, INPUT_PULLUP);",
      ],
      loop: [
        "int {ref}Clk = digitalRead({REF}_CLK);",
        "if ({ref}Clk != {ref}LastClk && {ref}Clk == LOW) {",
        "  {ref}Position += (digitalRead({REF}_DT) != {ref}Clk) ? 1 : -1;",
        "}",
        "{ref}LastClk = {ref}Clk;",
      ],
    },
    readingVar: "{ref}Position",
    buildTip: "If the count moves two steps per detent, only act on the falling edge of CLK (as this code does).",
  },
];

export const byId = (id: string): CatalogComponent => {
  const c = CATALOG.find((x) => x.id === id);
  if (!c) throw new Error(`Unknown component: ${id}`);
  return c;
};
