import { BOARDS } from "./boards";
import type { Behavior, BoardId, PlacedComponent } from "./types";

const fill = (line: string, pc: PlacedComponent) => {
  let out = line
    .replaceAll("{REF}", pc.refName.toUpperCase())
    .replaceAll("{ref}", pc.refName.charAt(0).toLowerCase() + pc.refName.slice(1))
    .replaceAll("{uint8_t}", "uint8_t");
  out = out.replace(/\{PIN:([A-Z]+)\}/g, (_, pinName: string) => {
    const pin = pc.pins.find((p) => p.name === pinName);
    return pin ? pinLabelToCode(pin.boardPin) : "0";
  });
  return out;
};

function pinLabelToCode(label: string): string {
  if (/^D\d+$/.test(label)) return label.slice(1);
  if (/^GPIO\d+$/.test(label)) return label.slice(4);
  if (/^GP\d+$/.test(label)) return label.slice(2);
  return label;
}

const refVar = (pc: PlacedComponent) =>
  pc.refName.charAt(0).toLowerCase() + pc.refName.slice(1);

function behaviorCode(b: Behavior, comps: PlacedComponent[]): string[] {
  const sensor = comps.find((c) => c.component.id === b.sensorId);
  const actuator = comps.find((c) => c.component.id === b.actuatorId);
  if (!sensor?.component.readingVar || !actuator?.component.actuate) return [];
  const reading = sensor.component.readingVar.replaceAll("{ref}", refVar(sensor));
  const on = fill(actuator.component.actuate.on, actuator);
  const off = fill(actuator.component.actuate.off, actuator);
  const isBool = reading.endsWith("Pressed") || reading.endsWith("Motion") || reading.endsWith("CardPresent");
  const cond = isBool ? reading : `${reading} ${b.comparator} ${b.threshold}`;
  return [
    `  // ${b.description}`,
    `  if (${cond}) {`,
    `    ${on}`,
    `  } else {`,
    `    ${off}`,
    `  }`,
  ];
}

function oledDashboard(comps: PlacedComponent[]): string[] {
  const oled = comps.find((c) => c.component.id === "oled");
  if (!oled) return [];
  const o = refVar(oled);
  const lines: string[] = [
    `  // Refresh the display with live readings`,
    `  ${o}.clearDisplay();`,
    `  ${o}.setCursor(0, 0);`,
  ];
  let row = 0;
  for (const c of comps) {
    if (!c.component.readingVar || row >= 5) continue;
    const v = c.component.readingVar.replaceAll("{ref}", refVar(c));
    lines.push(`  ${o}.setCursor(0, ${row * 12});`);
    lines.push(`  ${o}.print("${c.component.shortName}: "); ${o}.println(${v});`);
    row++;
  }
  if (row === 0) {
    lines.push(`  ${o}.println("Hello from Wirecraft!");`);
  }
  lines.push(`  ${o}.display();`);
  return lines;
}

export function generateCode(
  boardId: BoardId,
  name: string,
  prompt: string,
  comps: PlacedComponent[],
  behaviors: Behavior[],
): { code: string; platformioIni: string } {
  const board = BOARDS[boardId];

  const includes = new Set<string>(["#include <Arduino.h>"]);
  const defines: string[] = [];
  const globals: string[] = [];
  const setup: string[] = [];
  const loop: string[] = [];
  const helpers = new Set<string>();

  for (const pc of comps) {
    for (const l of pc.component.code.includes) includes.add(l);
    for (const l of pc.component.code.defines ?? []) defines.push(fill(l, pc));
    for (const l of pc.component.code.globals) globals.push(fill(l, pc));
    for (const l of pc.component.code.setup) setup.push("  " + fill(l, pc));
    for (const l of pc.component.code.loop) loop.push("  " + fill(l, pc));
    if (pc.component.code.helpers) {
      helpers.add(pc.component.code.helpers.map((l) => fill(l, pc)).join("\n"));
    }
  }

  const behaviorLines = behaviors.flatMap((b) => behaviorCode(b, comps));
  const dashboard = oledDashboard(comps);

  const code = [
    `// ${name}`,
    `// Generated by Wirecraft for the ${board.label} (${board.chip})`,
    `// Prompt: ${prompt.replace(/\n/g, " ").slice(0, 120)}`,
    `//`,
    `// Wiring, parts and step-by-step assembly live alongside this file.`,
    ``,
    ...[...includes],
    ``,
    ...(defines.length ? [...defines, ``] : []),
    ...(globals.length ? [...globals, ``] : []),
    ...(helpers.size ? [[...helpers].join("\n\n"), ``] : []),
    `void setup() {`,
    `  Serial.begin(115200);`,
    ...setup,
    `  Serial.println(F("${name} ready."));`,
    `}`,
    ``,
    `void loop() {`,
    ...(loop.length ? [`  // --- Read sensors ---`, ...loop, ``] : []),
    ...(behaviorLines.length ? [`  // --- React ---`, ...behaviorLines, ``] : []),
    ...(dashboard.length ? [...dashboard, ``] : []),
    `  delay(${comps.some((c) => c.component.id === "dht22") ? 2000 : 50});`,
    `}`,
    ``,
  ].join("\n");

  const libs = [...new Set(comps.flatMap((c) => c.component.libs))];
  const platformioIni = [
    `; PlatformIO project for ${name}`,
    `[env:${board.pioBoard}]`,
    `platform = ${board.pioPlatform}`,
    `board = ${board.pioBoard}`,
    `framework = arduino`,
    `monitor_speed = 115200`,
    ...(libs.length ? [`lib_deps =`, ...libs.map((l) => `\t${l}`)] : []),
    ``,
  ].join("\n");

  return { code, platformioIni };
}
